package com.moda.demo.entity;

import com.moda.entity.BaseEntity;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table usr_user
 */
public class User extends BaseEntity {
    /**
     * Database Column Remarks:
     *   ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_user.id
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   用户名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_user.username
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    private String username;

    /**
     * Database Column Remarks:
     *   姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_user.name
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    private String name;

    /**
     * Database Column Remarks:
     *   昵称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_user.nickname
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    private String nickname;

    /**
     * Database Column Remarks:
     *   手机号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_user.mobile
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    private String mobile;

    /**
     * Database Column Remarks:
     *   邮箱
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_user.email
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    private String email;

    /**
     * Database Column Remarks:
     *   密码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_user.password
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    private String password;

    /**
     * Database Column Remarks:
     *   状态：0-禁用；1-正常
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_user.status
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    private Integer status;

    /**
     * Database Column Remarks:
     *   访问令牌
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_user.access_token
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    private String accessToken;

    /**
     * Database Column Remarks:
     *   微信openid
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_user.open_id
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    private String openId;

    /**
     * Database Column Remarks:
     *   注册时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_user.reg_time
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    private Date regTime;

    /**
     * Database Column Remarks:
     *   支付密码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_user.pay_password
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    private String payPassword;

    /**
     * Database Column Remarks:
     *   身份证号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_user.id_no
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    private String idNo;

    /**
     * Database Column Remarks:
     *   身份证照片
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_user.id_url
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    private String idUrl;

    /**
     * Database Column Remarks:
     *   认证状态：1-认证中；2-认证通过；3-认证失败
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_user.auth_status
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    private Integer authStatus;

    /**
     * Database Column Remarks:
     *   邀请码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_user.invitation_code
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    private String invitationCode;

    /**
     * Database Column Remarks:
     *   头像地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_user.head_url
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    private String headUrl;

    /**
     * Database Column Remarks:
     *   用户类型：1-一般用户；2-酒店前台用户；3-后台管理系统用户；4-运营用户；5-
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_user.type
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    private Byte type;

    /**
     * Database Column Remarks:
     *   性别：1-男；2-女
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_user.sex
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    private Byte sex;

    /**
     * Database Column Remarks:
     *   生日
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_user.birthday
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    private Date birthday;

    /**
     * Database Column Remarks:
     *   省代码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_user.province_code
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    private String provinceCode;

    /**
     * Database Column Remarks:
     *   市代码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_user.city_code
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    private String cityCode;

    /**
     * Database Column Remarks:
     *   区代码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_user.district_code
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    private String districtCode;

    /**
     * Database Column Remarks:
     *   省市区名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_user.region_name
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    private String regionName;

    /**
     * Database Column Remarks:
     *   省份ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_user.province_id
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    private Integer provinceId;

    /**
     * Database Column Remarks:
     *   城市ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_user.city_id
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    private Integer cityId;

    /**
     * Database Column Remarks:
     *   区县ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_user.district_id
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    private Integer districtId;

    /**
     * Database Column Remarks:
     *   版本
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_user.version
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_user.id
     *
     * @return the value of usr_user.id
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_user.id
     *
     * @param id the value for usr_user.id
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_user.username
     *
     * @return the value of usr_user.username
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_user.username
     *
     * @param username the value for usr_user.username
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_user.name
     *
     * @return the value of usr_user.name
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_user.name
     *
     * @param name the value for usr_user.name
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_user.nickname
     *
     * @return the value of usr_user.nickname
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_user.nickname
     *
     * @param nickname the value for usr_user.nickname
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_user.mobile
     *
     * @return the value of usr_user.mobile
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_user.mobile
     *
     * @param mobile the value for usr_user.mobile
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_user.email
     *
     * @return the value of usr_user.email
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_user.email
     *
     * @param email the value for usr_user.email
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_user.password
     *
     * @return the value of usr_user.password
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_user.password
     *
     * @param password the value for usr_user.password
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_user.status
     *
     * @return the value of usr_user.status
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_user.status
     *
     * @param status the value for usr_user.status
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_user.access_token
     *
     * @return the value of usr_user.access_token
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    public String getAccessToken() {
        return accessToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_user.access_token
     *
     * @param accessToken the value for usr_user.access_token
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    public void setAccessToken(String accessToken) {
        this.accessToken = accessToken == null ? null : accessToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_user.open_id
     *
     * @return the value of usr_user.open_id
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_user.open_id
     *
     * @param openId the value for usr_user.open_id
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_user.reg_time
     *
     * @return the value of usr_user.reg_time
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    public Date getRegTime() {
        return regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_user.reg_time
     *
     * @param regTime the value for usr_user.reg_time
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    public void setRegTime(Date regTime) {
        this.regTime = regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_user.pay_password
     *
     * @return the value of usr_user.pay_password
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    public String getPayPassword() {
        return payPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_user.pay_password
     *
     * @param payPassword the value for usr_user.pay_password
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    public void setPayPassword(String payPassword) {
        this.payPassword = payPassword == null ? null : payPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_user.id_no
     *
     * @return the value of usr_user.id_no
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    public String getIdNo() {
        return idNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_user.id_no
     *
     * @param idNo the value for usr_user.id_no
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    public void setIdNo(String idNo) {
        this.idNo = idNo == null ? null : idNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_user.id_url
     *
     * @return the value of usr_user.id_url
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    public String getIdUrl() {
        return idUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_user.id_url
     *
     * @param idUrl the value for usr_user.id_url
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    public void setIdUrl(String idUrl) {
        this.idUrl = idUrl == null ? null : idUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_user.auth_status
     *
     * @return the value of usr_user.auth_status
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    public Integer getAuthStatus() {
        return authStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_user.auth_status
     *
     * @param authStatus the value for usr_user.auth_status
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    public void setAuthStatus(Integer authStatus) {
        this.authStatus = authStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_user.invitation_code
     *
     * @return the value of usr_user.invitation_code
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    public String getInvitationCode() {
        return invitationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_user.invitation_code
     *
     * @param invitationCode the value for usr_user.invitation_code
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    public void setInvitationCode(String invitationCode) {
        this.invitationCode = invitationCode == null ? null : invitationCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_user.head_url
     *
     * @return the value of usr_user.head_url
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    public String getHeadUrl() {
        return headUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_user.head_url
     *
     * @param headUrl the value for usr_user.head_url
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    public void setHeadUrl(String headUrl) {
        this.headUrl = headUrl == null ? null : headUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_user.type
     *
     * @return the value of usr_user.type
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_user.type
     *
     * @param type the value for usr_user.type
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_user.sex
     *
     * @return the value of usr_user.sex
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    public Byte getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_user.sex
     *
     * @param sex the value for usr_user.sex
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    public void setSex(Byte sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_user.birthday
     *
     * @return the value of usr_user.birthday
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_user.birthday
     *
     * @param birthday the value for usr_user.birthday
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_user.province_code
     *
     * @return the value of usr_user.province_code
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    public String getProvinceCode() {
        return provinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_user.province_code
     *
     * @param provinceCode the value for usr_user.province_code
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    public void setProvinceCode(String provinceCode) {
        this.provinceCode = provinceCode == null ? null : provinceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_user.city_code
     *
     * @return the value of usr_user.city_code
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_user.city_code
     *
     * @param cityCode the value for usr_user.city_code
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode == null ? null : cityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_user.district_code
     *
     * @return the value of usr_user.district_code
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    public String getDistrictCode() {
        return districtCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_user.district_code
     *
     * @param districtCode the value for usr_user.district_code
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    public void setDistrictCode(String districtCode) {
        this.districtCode = districtCode == null ? null : districtCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_user.region_name
     *
     * @return the value of usr_user.region_name
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    public String getRegionName() {
        return regionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_user.region_name
     *
     * @param regionName the value for usr_user.region_name
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    public void setRegionName(String regionName) {
        this.regionName = regionName == null ? null : regionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_user.province_id
     *
     * @return the value of usr_user.province_id
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    public Integer getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_user.province_id
     *
     * @param provinceId the value for usr_user.province_id
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    public void setProvinceId(Integer provinceId) {
        this.provinceId = provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_user.city_id
     *
     * @return the value of usr_user.city_id
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_user.city_id
     *
     * @param cityId the value for usr_user.city_id
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_user.district_id
     *
     * @return the value of usr_user.district_id
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    public Integer getDistrictId() {
        return districtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_user.district_id
     *
     * @param districtId the value for usr_user.district_id
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    public void setDistrictId(Integer districtId) {
        this.districtId = districtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_user.version
     *
     * @return the value of usr_user.version
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_user.version
     *
     * @param version the value for usr_user.version
     *
     * @mbg.generated Mon Apr 29 18:40:59 CST 2019
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}