package com.moda.demo.entity;

import com.moda.entity.BaseEntity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_area
 */
public class Area extends BaseEntity {
    /**
     * Database Column Remarks:
     *   ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_area.id
     *
     * @mbg.generated Tue Apr 30 15:55:05 CST 2019
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   父级ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_area.parent_id
     *
     * @mbg.generated Tue Apr 30 15:55:05 CST 2019
     */
    private Integer parentId;

    /**
     * Database Column Remarks:
     *   合并的ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_area.merger_id
     *
     * @mbg.generated Tue Apr 30 15:55:05 CST 2019
     */
    private String mergerId;

    /**
     * Database Column Remarks:
     *   父级code
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_area.parent_code
     *
     * @mbg.generated Tue Apr 30 15:55:05 CST 2019
     */
    private String parentCode;

    /**
     * Database Column Remarks:
     *   编码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_area.code
     *
     * @mbg.generated Tue Apr 30 15:55:05 CST 2019
     */
    private String code;

    /**
     * Database Column Remarks:
     *   名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_area.name
     *
     * @mbg.generated Tue Apr 30 15:55:05 CST 2019
     */
    private String name;

    /**
     * Database Column Remarks:
     *   简称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_area.short_name
     *
     * @mbg.generated Tue Apr 30 15:55:05 CST 2019
     */
    private String shortName;

    /**
     * Database Column Remarks:
     *   排序：升序
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_area.sort
     *
     * @mbg.generated Tue Apr 30 15:55:05 CST 2019
     */
    private Integer sort;

    /**
     * Database Column Remarks:
     *   区域类型（0：国家；1：省份、直辖市；2：地市；3：区县）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_area.type
     *
     * @mbg.generated Tue Apr 30 15:55:05 CST 2019
     */
    private Integer type;

    /**
     * Database Column Remarks:
     *   行政代码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_area.city_code
     *
     * @mbg.generated Tue Apr 30 15:55:05 CST 2019
     */
    private String cityCode;

    /**
     * Database Column Remarks:
     *   邮政编码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_area.zip_code
     *
     * @mbg.generated Tue Apr 30 15:55:05 CST 2019
     */
    private String zipCode;

    /**
     * Database Column Remarks:
     *   合并的名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_area.merger_name
     *
     * @mbg.generated Tue Apr 30 15:55:05 CST 2019
     */
    private String mergerName;

    /**
     * Database Column Remarks:
     *   经度
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_area.lng
     *
     * @mbg.generated Tue Apr 30 15:55:05 CST 2019
     */
    private Float lng;

    /**
     * Database Column Remarks:
     *   纬度
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_area.lat
     *
     * @mbg.generated Tue Apr 30 15:55:05 CST 2019
     */
    private Float lat;

    /**
     * Database Column Remarks:
     *   拼音
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_area.pinyin
     *
     * @mbg.generated Tue Apr 30 15:55:05 CST 2019
     */
    private String pinyin;

    /**
     * Database Column Remarks:
     *   是否显示：0-否；1-是
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_area.is_show
     *
     * @mbg.generated Tue Apr 30 15:55:05 CST 2019
     */
    private Integer isShow;

    /**
     * Database Column Remarks:
     *   备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_area.remarks
     *
     * @mbg.generated Tue Apr 30 15:55:05 CST 2019
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_area.id
     *
     * @return the value of sys_area.id
     *
     * @mbg.generated Tue Apr 30 15:55:05 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_area.id
     *
     * @param id the value for sys_area.id
     *
     * @mbg.generated Tue Apr 30 15:55:05 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_area.parent_id
     *
     * @return the value of sys_area.parent_id
     *
     * @mbg.generated Tue Apr 30 15:55:05 CST 2019
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_area.parent_id
     *
     * @param parentId the value for sys_area.parent_id
     *
     * @mbg.generated Tue Apr 30 15:55:05 CST 2019
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_area.merger_id
     *
     * @return the value of sys_area.merger_id
     *
     * @mbg.generated Tue Apr 30 15:55:05 CST 2019
     */
    public String getMergerId() {
        return mergerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_area.merger_id
     *
     * @param mergerId the value for sys_area.merger_id
     *
     * @mbg.generated Tue Apr 30 15:55:05 CST 2019
     */
    public void setMergerId(String mergerId) {
        this.mergerId = mergerId == null ? null : mergerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_area.parent_code
     *
     * @return the value of sys_area.parent_code
     *
     * @mbg.generated Tue Apr 30 15:55:05 CST 2019
     */
    public String getParentCode() {
        return parentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_area.parent_code
     *
     * @param parentCode the value for sys_area.parent_code
     *
     * @mbg.generated Tue Apr 30 15:55:05 CST 2019
     */
    public void setParentCode(String parentCode) {
        this.parentCode = parentCode == null ? null : parentCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_area.code
     *
     * @return the value of sys_area.code
     *
     * @mbg.generated Tue Apr 30 15:55:05 CST 2019
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_area.code
     *
     * @param code the value for sys_area.code
     *
     * @mbg.generated Tue Apr 30 15:55:05 CST 2019
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_area.name
     *
     * @return the value of sys_area.name
     *
     * @mbg.generated Tue Apr 30 15:55:05 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_area.name
     *
     * @param name the value for sys_area.name
     *
     * @mbg.generated Tue Apr 30 15:55:05 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_area.short_name
     *
     * @return the value of sys_area.short_name
     *
     * @mbg.generated Tue Apr 30 15:55:05 CST 2019
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_area.short_name
     *
     * @param shortName the value for sys_area.short_name
     *
     * @mbg.generated Tue Apr 30 15:55:05 CST 2019
     */
    public void setShortName(String shortName) {
        this.shortName = shortName == null ? null : shortName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_area.sort
     *
     * @return the value of sys_area.sort
     *
     * @mbg.generated Tue Apr 30 15:55:05 CST 2019
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_area.sort
     *
     * @param sort the value for sys_area.sort
     *
     * @mbg.generated Tue Apr 30 15:55:05 CST 2019
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_area.type
     *
     * @return the value of sys_area.type
     *
     * @mbg.generated Tue Apr 30 15:55:05 CST 2019
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_area.type
     *
     * @param type the value for sys_area.type
     *
     * @mbg.generated Tue Apr 30 15:55:05 CST 2019
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_area.city_code
     *
     * @return the value of sys_area.city_code
     *
     * @mbg.generated Tue Apr 30 15:55:05 CST 2019
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_area.city_code
     *
     * @param cityCode the value for sys_area.city_code
     *
     * @mbg.generated Tue Apr 30 15:55:05 CST 2019
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode == null ? null : cityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_area.zip_code
     *
     * @return the value of sys_area.zip_code
     *
     * @mbg.generated Tue Apr 30 15:55:05 CST 2019
     */
    public String getZipCode() {
        return zipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_area.zip_code
     *
     * @param zipCode the value for sys_area.zip_code
     *
     * @mbg.generated Tue Apr 30 15:55:05 CST 2019
     */
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode == null ? null : zipCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_area.merger_name
     *
     * @return the value of sys_area.merger_name
     *
     * @mbg.generated Tue Apr 30 15:55:05 CST 2019
     */
    public String getMergerName() {
        return mergerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_area.merger_name
     *
     * @param mergerName the value for sys_area.merger_name
     *
     * @mbg.generated Tue Apr 30 15:55:05 CST 2019
     */
    public void setMergerName(String mergerName) {
        this.mergerName = mergerName == null ? null : mergerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_area.lng
     *
     * @return the value of sys_area.lng
     *
     * @mbg.generated Tue Apr 30 15:55:05 CST 2019
     */
    public Float getLng() {
        return lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_area.lng
     *
     * @param lng the value for sys_area.lng
     *
     * @mbg.generated Tue Apr 30 15:55:05 CST 2019
     */
    public void setLng(Float lng) {
        this.lng = lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_area.lat
     *
     * @return the value of sys_area.lat
     *
     * @mbg.generated Tue Apr 30 15:55:05 CST 2019
     */
    public Float getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_area.lat
     *
     * @param lat the value for sys_area.lat
     *
     * @mbg.generated Tue Apr 30 15:55:05 CST 2019
     */
    public void setLat(Float lat) {
        this.lat = lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_area.pinyin
     *
     * @return the value of sys_area.pinyin
     *
     * @mbg.generated Tue Apr 30 15:55:05 CST 2019
     */
    public String getPinyin() {
        return pinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_area.pinyin
     *
     * @param pinyin the value for sys_area.pinyin
     *
     * @mbg.generated Tue Apr 30 15:55:05 CST 2019
     */
    public void setPinyin(String pinyin) {
        this.pinyin = pinyin == null ? null : pinyin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_area.is_show
     *
     * @return the value of sys_area.is_show
     *
     * @mbg.generated Tue Apr 30 15:55:05 CST 2019
     */
    public Integer getIsShow() {
        return isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_area.is_show
     *
     * @param isShow the value for sys_area.is_show
     *
     * @mbg.generated Tue Apr 30 15:55:05 CST 2019
     */
    public void setIsShow(Integer isShow) {
        this.isShow = isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_area.remarks
     *
     * @return the value of sys_area.remarks
     *
     * @mbg.generated Tue Apr 30 15:55:05 CST 2019
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_area.remarks
     *
     * @param remarks the value for sys_area.remarks
     *
     * @mbg.generated Tue Apr 30 15:55:05 CST 2019
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}