package com.moda.demo;

import com.alibaba.fastjson.JSONObject;
import com.moda.util.http.HttpClientUtils;
import com.moda.util.lang.StringUtils;
import com.moda.util.mapper.JsonMapper;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.atomic.AtomicInteger;

@RunWith(SpringRunner.class)
@SpringBootTest
public class AppTest {

    @Test
    public void test() {

        String url = "https://checkapi.aliyun.com/check/checkdomain?domain=%s&token=Y1da229242e5af26f0687db0ca231794d";
        String domain = "sex.tech\n" +
                "business.tech\n" +
                "travel.tech\n" +
                "money.tech\n" +
                "music.tech\n" +
                "info.tech\n" +
                "free.tech\n" +
                "law.tech\n" +
                "my.tech\n" +
                "stocks.tech\n" +
                "web.tech\n" +
                "computer.tech\n" +
                "loans.tech\n" +
                "america.tech\n" +
                "china.tech\n" +
                "stock.tech\n" +
                "japan.tech\n" +
                "game.tech\n" +
                "trade.tech\n" +
                "games.tech\n" +
                "show.tech\n" +
                "usa.tech\n" +
                "news.tech\n" +
                "internet.tech\n" +
                "health.tech\n" +
                "insurance.tech\n" +
                "tv.tech\n" +
                "auto.tech\n" +
                "wireless.tech\n" +
                "biz.tech\n" +
                "mortgage.tech\n" +
                "shop.tech\n" +
                "software.tech\n" +
                "food.tech\n" +
                "tax.tech\n" +
                "casino.tech\n" +
                "domain.tech\n" +
                "email.tech\n" +
                "beauty.tech\n" +
                "finance.tech\n" +
                "realestate.tech\n" +
                "car.tech\n" +
                "sports.tech\n" +
                "bank.tech\n" +
                "loan.tech\n" +
                "buy.tech\n" +
                "europe.tech\n" +
                "home.tech\n" +
                "cars.tech\n" +
                "net.tech\n" +
                "jobs.tech\n" +
                "korea.tech\n" +
                "drugs.tech\n" +
                "art.tech\n" +
                "love.tech\n" +
                "homes.tech\n" +
                "pc.tech\n" +
                "medicine.tech\n" +
                "www.tech\n" +
                "xxx.tech\n" +
                "books.tech\n" +
                "canada.tech\n" +
                "search.tech\n" +
                "mail.tech\n" +
                "world.tech\n" +
                "computers.tech\n" +
                "wallstreet.tech\n" +
                "football.tech\n" +
                "sales.tech\n" +
                "video.tech\n" +
                "movies.tech\n" +
                "movie.tech\n" +
                "auction.tech\n" +
                "hotel.tech\n" +
                "weather.tech\n" +
                "fashion.tech\n" +
                "gambling.tech\n" +
                "california.tech\n" +
                "lawyer.tech\n" +
                "mexico.tech\n" +
                "shopping.tech\n" +
                "dvd.tech\n" +
                "newyork.tech\n" +
                "us.tech\n" +
                "medical.tech\n" +
                "online.tech\n" +
                "india.tech\n" +
                "porn.tech\n" +
                "golf.tech\n" +
                "asia.tech\n" +
                "market.tech\n" +
                "book.tech\n" +
                "sport.tech\n" +
                "lasvegas.tech\n" +
                "uk.tech\n" +
                "hot.tech\n" +
                "marketing.tech\n" +
                "hollywood.tech\n" +
                "film.tech\n" +
                "job.tech\n" +
                "mobile.tech\n" +
                "wine.tech\n" +
                "credit.tech\n" +
                "it.tech\n" +
                "holiday.tech\n" +
                "commerce.tech\n" +
                "network.tech\n" +
                "cinema.tech\n" +
                "go.tech\n" +
                "best.tech\n" +
                "hongkong.tech\n" +
                "mp3.tech\n" +
                "com.tech\n" +
                "cool.tech\n" +
                "sale.tech\n" +
                "gold.tech\n" +
                "sell.tech\n" +
                "security.tech\n" +
                "australia.tech\n" +
                "design.tech\n" +
                "phone.tech\n" +
                "thailand.tech\n" +
                "tickets.tech\n" +
                "ticket.tech\n" +
                "diet.tech\n" +
                "ecommerce.tech\n" +
                "autos.tech\n" +
                "gay.tech\n" +
                "stockmarket.tech\n" +
                "ebusiness.tech\n" +
                "africa.tech\n" +
                "porno.tech\n" +
                "germany.tech\n" +
                "legal.tech\n" +
                "find.tech\n" +
                "help.tech\n" +
                "media.tech\n" +
                "cash.tech\n" +
                "drug.tech\n" +
                "b2b.tech\n" +
                "radio.tech\n" +
                "women.tech\n" +
                "doctor.tech\n" +
                "la.tech\n" +
                "banking.tech\n" +
                "broadband.tech\n" +
                "consulting.tech\n" +
                "entertainment.tech\n" +
                "fitness.tech\n" +
                "soccer.tech\n" +
                "england.tech\n" +
                "college.tech\n" +
                "register.tech\n" +
                "brazil.tech\n" +
                "france.tech\n" +
                "creditcard.tech\n" +
                "baseball.tech\n" +
                "tennis.tech\n" +
                "jewelry.tech\n" +
                "technology.tech\n" +
                "losangeles.tech\n" +
                "chinese.tech\n" +
                "london.tech\n" +
                "domains.tech\n" +
                "hardware.tech\n" +
                "tokyo.tech\n" +
                "tour.tech\n" +
                "kids.tech\n" +
                "live.tech\n" +
                "family.tech\n" +
                "advertising.tech\n" +
                "toys.tech\n" +
                "webdesign.tech\n" +
                "house.tech\n" +
                "employment.tech\n" +
                "adult.tech\n" +
                "the.tech\n" +
                "fun.tech\n" +
                "directory.tech\n" +
                "pharmacy.tech\n" +
                "hosting.tech\n" +
                "indonesia.tech\n" +
                "taiwan.tech\n" +
                "fishing.tech\n" +
                "financial.tech\n" +
                "hawaii.tech\n" +
                "english.tech\n" +
                "florida.tech\n" +
                "flowers.tech\n" +
                "global.tech\n" +
                "girl.tech\n" +
                "italy.tech\n" +
                "investment.tech\n" +
                "basketball.tech\n" +
                "chat.tech\n" +
                "tech.tech\n" +
                "healthcare.tech\n" +
                "mutualfunds.tech\n" +
                "webhosting.tech\n" +
                "hotels.tech\n" +
                "turkey.tech\n" +
                "christmas.tech\n" +
                "divorce.tech\n" +
                "ad.tech\n" +
                "club.tech\n" +
                "digital.tech\n" +
                "engineering.tech\n" +
                "test.tech\n" +
                "baby.tech\n" +
                "bonds.tech\n" +
                "rent.tech\n" +
                "sexy.tech\n" +
                "education.tech\n" +
                "paris.tech\n" +
                "cancer.tech\n" +
                "city.tech\n" +
                "boy.tech\n" +
                "photo.tech\n" +
                "chicago.tech\n" +
                "american.tech\n" +
                "top.tech\n" +
                "cruise.tech\n" +
                "broker.tech\n" +
                "accounting.tech\n" +
                "pro.tech\n" +
                "bio.tech\n" +
                "attorney.tech\n" +
                "hockey.tech\n" +
                "cd.tech\n" +
                "taxes.tech\n" +
                "girls.tech\n" +
                "lawyers.tech\n" +
                "toy.tech\n" +
                "texas.tech\n" +
                "information.tech\n" +
                "auctions.tech\n" +
                "lottery.tech\n" +
                "forsale.tech\n" +
                "woman.tech\n" +
                "god.tech\n" +
                "gifts.tech\n" +
                "delivery.tech\n" +
                "russia.tech\n" +
                "all.tech\n" +
                "wedding.tech\n" +
                "vacation.tech\n" +
                "euro.tech\n" +
                "shipping.tech\n" +
                "argentina.tech\n" +
                "mall.tech\n" +
                "newzealand.tech\n" +
                "gas.tech\n" +
                "invest.tech\n" +
                "spain.tech\n" +
                "television.tech\n" +
                "restaurant.tech\n" +
                "construction.tech\n" +
                "university.tech\n" +
                "map.tech\n" +
                "press.tech\n" +
                "trading.tech\n" +
                "capital.tech\n" +
                "hk.tech\n" +
                "realty.tech\n" +
                "genome.tech\n" +
                "retirement.tech\n" +
                "singapore.tech\n" +
                "alaska.tech\n" +
                "coffee.tech\n" +
                "company.tech\n" +
                "drugstore.tech\n" +
                "oil.tech\n" +
                "furniture.tech\n" +
                "pets.tech\n" +
                "diamond.tech\n" +
                "career.tech\n" +
                "beer.tech\n" +
                "fly.tech\n" +
                "nyc.tech\n" +
                "life.tech\n" +
                "biotech.tech\n" +
                "get.tech\n" +
                "islam.tech\n" +
                "bankruptcy.tech\n" +
                "3g.tech\n" +
                "pop.tech\n" +
                "antiques.tech\n" +
                "holidays.tech\n" +
                "gift.tech\n" +
                "cards.tech\n" +
                "ski.tech\n" +
                "school.tech\n" +
                "washington.tech\n" +
                "pussy.tech\n" +
                "commercial.tech\n" +
                "casinos.tech\n" +
                "beautiful.tech\n" +
                "dogs.tech\n" +
                "dna.tech\n" +
                "people.tech\n" +
                "first.tech\n" +
                "diamonds.tech\n" +
                "water.tech\n" +
                "pda.tech\n" +
                "power.tech\n" +
                "your.tech\n" +
                "tourist.tech\n" +
                "play.tech\n" +
                "pizza.tech\n" +
                "office.tech\n" +
                "boston.tech\n" +
                "malaysia.tech\n" +
                "air.tech\n" +
                "cuba.tech\n" +
                "cooking.tech\n" +
                "big.tech\n" +
                "asian.tech\n" +
                "biotechnology.tech\n" +
                "bible.tech\n" +
                "audio.tech\n" +
                "madrid.tech\n" +
                "student.tech\n" +
                "new.tech\n" +
                "seattle.tech\n" +
                "401k.tech\n" +
                "men.tech\n" +
                "chile.tech\n" +
                "personal.tech\n" +
                "personalinjury.tech\n" +
                "airline.tech\n" +
                "cats.tech\n" +
                "cat.tech\n" +
                "wap.tech\n" +
                "3d.tech\n" +
                "general.tech\n" +
                "theater.tech\n" +
                "miami.tech\n" +
                "investing.tech\n" +
                "nz.tech\n" +
                "energy.tech\n" +
                "international.tech\n" +
                "restaurants.tech\n" +
                "doctors.tech\n" +
                "more.tech\n" +
                "cosmetics.tech\n" +
                "hospital.tech\n" +
                "name.tech\n" +
                "electronics.tech\n" +
                "telecom.tech\n" +
                "istanbul.tech\n" +
                "photography.tech\n" +
                "israel.tech\n" +
                "host.tech\n" +
                "exchange.tech\n" +
                "cn.tech\n" +
                "dot.tech\n" +
                "maps.tech\n" +
                "government.tech\n" +
                "flower.tech\n" +
                "switzerland.tech\n" +
                "model.tech\n" +
                "arizona.tech\n" +
                "traffic.tech\n" +
                "whois.tech\n" +
                "emoney.tech\n" +
                "consumer.tech\n" +
                "realtor.tech\n" +
                "apartment.tech\n" +
                "research.tech\n" +
                "ny.tech\n" +
                "management.tech\n" +
                "flight.tech\n" +
                "cellular.tech\n" +
                "models.tech\n" +
                "jazz.tech\n" +
                "banks.tech\n" +
                "pet.tech\n" +
                "sanfrancisco.tech\n" +
                "download.tech\n" +
                "ebiz.tech\n" +
                "dating.tech\n" +
                "atlanta.tech\n" +
                "ireland.tech\n" +
                "corporate.tech\n" +
                "ca.tech\n" +
                "holland.tech\n" +
                "clubs.tech\n" +
                "vitamins.tech\n" +
                "virginia.tech\n" +
                "export.tech\n" +
                "express.tech\n" +
                "healthinsurance.tech\n" +
                "blackjack.tech\n" +
                "greece.tech\n" +
                "hobbies.tech\n" +
                "abc.tech\n" +
                "seoul.tech\n" +
                "time.tech\n" +
                "hair.tech\n" +
                "lotto.tech\n" +
                "erotic.tech\n" +
                "etrade.tech\n" +
                "man.tech\n" +
                "architecture.tech\n" +
                "domainnames.tech\n" +
                "silver.tech\n" +
                "work.tech\n" +
                "unitedstates.tech\n" +
                "success.tech\n" +
                "dog.tech\n" +
                "boat.tech\n" +
                "massachusetts.tech\n" +
                "property.tech\n" +
                "smart.tech\n" +
                "trademark.tech\n" +
                "html.tech\n" +
                "in.tech\n" +
                "venture.tech\n" +
                "franchise.tech\n" +
                "lesbian.tech\n" +
                "sound.tech\n" +
                "arab.tech\n" +
                "monkey.tech\n" +
                "webmaster.tech\n" +
                "cafe.tech\n" +
                "creditcards.tech\n" +
                "cpa.tech\n" +
                "newspaper.tech\n" +
                "no.tech\n" +
                "apartments.tech\n" +
                "gaming.tech\n" +
                "gamble.tech\n" +
                "happy.tech\n" +
                "consultant.tech\n" +
                "arts.tech\n" +
                "financing.tech\n" +
                "fish.tech\n" +
                "houston.tech\n" +
                "vietnam.tech\n" +
                "style.tech\n" +
                "patent.tech\n" +
                "camera.tech\n" +
                "amsterdam.tech\n" +
                "bet.tech\n" +
                "networks.tech\n" +
                "stockbroker.tech\n" +
                "date.tech\n" +
                "wines.tech\n" +
                "cyber.tech\n" +
                "vacations.tech\n" +
                "trucks.tech\n" +
                "barcelona.tech\n" +
                "angel.tech\n" +
                "shoes.tech\n" +
                "space.tech\n" +
                "finland.tech\n" +
                "isp.tech\n" +
                "kid.tech\n" +
                "party.tech\n" +
                "alabama.tech\n" +
                "star.tech\n" +
                "start.tech\n" +
                "sun.tech\n" +
                "idaho.tech\n" +
                "egypt.tech\n" +
                "shanghai.tech\n" +
                "on.tech\n" +
                "politics.tech\n" +
                "account.tech\n" +
                "md.tech\n" +
                "rome.tech\n" +
                "motorcycle.tech\n" +
                "orange.tech\n" +
                "data.tech\n" +
                "emoney.tech\n" +
                "med.tech\n" +
                "lease.tech\n" +
                "lebanon.tech\n" +
                "lifeinsurance.tech\n" +
                "iran.tech\n" +
                "jakarta.tech\n" +
                "ebuy.tech\n" +
                "homepage.tech\n" +
                "fax.tech\n" +
                "georgia.tech\n" +
                "astrology.tech\n" +
                "cruises.tech\n" +
                "yes.tech\n" +
                "airlines.tech\n" +
                "good.tech\n" +
                "land.tech\n" +
                "nutrition.tech\n" +
                "virtual.tech\n" +
                "camping.tech\n" +
                "master.tech\n" +
                "computing.tech\n" +
                "domainname.tech\n" +
                "discount.tech\n" +
                "multimedia.tech\n" +
                "psychology.tech\n" +
                "hobbies.tech\n" +
                "iran.tech\n" +
                "malaysia.tech\n" +
                "holland.tech\n" +
                "egypt.tech\n" +
                "cuba.tech\n" +
                "indonesia.tech\n" +
                "camping.tech\n" +
                "finland.tech\n" +
                "greece.tech\n" +
                "ebuy.tech\n" +
                "mutualfunds.tech\n" +
                "newzealand.tech\n" +
                "astrology.tech\n" +
                "biotech.tech\n" +
                "hospital.tech\n" +
                "switzerland.tech\n" +
                "bible.tech\n" +
                "singapore.tech\n" +
                "madrid.tech\n" +
                "argentina.tech\n" +
                "jakarta.tech\n" +
                "biotechnology.tech\n" +
                "monkey.tech\n" +
                "istanbul.tech\n" +
                "genome.tech\n" +
                "bonds.tech\n" +
                "islam.tech\n" +
                "trucks.tech\n" +
                "lebanon.tech\n" +
                "tourist.tech\n" +
                "theater.tech\n" +
                "russia.tech\n" +
                "flight.tech\n" +
                "architecture.tech\n" +
                "computing.tech\n" +
                "clubs.tech\n" +
                "orange.tech\n" +
                "israel.tech\n" +
                "politics.tech\n" +
                "ireland.tech\n" +
                "barcelona.tech\n" +
                "rome.tech\n" +
                "export.tech\n" +
                "amsterdam.tech\n" +
                "chile.tech";

        List<String> lstUnreg = new ArrayList<>();
        List<String> lst = StringUtils.splitOnly(domain, "\n");
        System.out.println("list.size=" + lst.size());
        int size = lst.size();
        AtomicInteger i = new AtomicInteger();
        lst.forEach(d -> {
            System.out.println(i.incrementAndGet() + "/" + size);
            try {
                String json = HttpClientUtils.get(String.format(url, d));
                JSONObject obj = JsonMapper.parseObject(json, JSONObject.class);
                JSONObject res = obj.getJSONArray("module").getJSONObject(0);
                Integer avalid = res.getInteger("avail");
                Integer price = res.getInteger("price");
                if (avalid == 1 && (price == null || price < 100)) {
                    lstUnreg.add(d);
                }
            } catch (IOException e) {
                e.printStackTrace();
            }
        });


        lstUnreg.forEach(System.out::println);
    }
}
